# Generated by Django 6.0.4 on 2026-04-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentblock',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='teacherblock',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/', verbose_name='Иконка'),
        ),
    ]
