# Generated by Django 6.0.4 on 2026-04-12 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_studentblock_icon_alter_teacherblock_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentblock',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Иконка (PNG, JPG, SVG)'),
        ),
        migrations.AlterField(
            model_name='teacherblock',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Иконка (PNG, JPG, SVG)'),
        ),
    ]
