# Generated by Django 6.0.4 on 2026-04-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_studentblock_icon_alter_teacherblock_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Обложка курса'),
        ),
    ]
