# Generated by Django 6.0.4 on 2026-04-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author_name',
            field=models.CharField(blank=True, default='Кит Макс', max_length=255, verbose_name='Автор курса'),
        ),
    ]
