# Generated by Django 6.0.4 on 2026-04-12 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author_name',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.author', verbose_name='Автор курса'),
        ),
    ]
